import random


def seletor_de_questao():
    instrucoes = [
    {"classId": "00000000-0000-0000-0000-000000000000", "quantity": 5,
     "habilidadeContext": {"habilidadeId": "EF02MA01", "unidadeTematica": {"nome": "Números"},
                           "prerequisites": ["EF02MA02", "EF02MA03"], "examples": []}, "_meta": {"ano": "segundo",
                                                                                                 "objeto_conhecimento": "Leitura, escrita, comparação e ordenação de números naturais de até três ordens",
                                                                                                 "descricao_habilidade": "Comparar e ordenar números naturais de até três ordens em situações do seu cotidiano, com e sem o suporte da reta numérica.",
                                                                                                 "prereqs_ilustrativos": True}},
    {"classId": "00000000-0000-0000-0000-000000000000", "quantity": 3,
     "habilidadeContext": {"habilidadeId": "EF02MA20", "unidadeTematica": {"nome": "Probabilidade e estatística"},
                           "prerequisites": ["EF02MA01", "EF02MA02"], "examples": []},
     "_meta": {"ano": "segundo", "objeto_conhecimento": "Classificação de eventos e construção de tabelas e gráficos",
               "descricao_habilidade": "Classificar eventos de seu cotidiano como possíveis, impossíveis ou garantidos.",
               "prereqs_ilustrativos": True}},
    {"classId": "00000000-0000-0000-0000-000000000000", "quantity": 5,
     "habilidadeContext": {"habilidadeId": "EF04MA08", "unidadeTematica": {"nome": "Álgebra"},
                           "prerequisites": ["EF04MA01", "EF04MA02"], "examples": []},
     "_meta": {"ano": "quarto", "objeto_conhecimento": "Sequências numéricas e proporcionalidade",
               "descricao_habilidade": "Identificar e descrever regularidades em sequências numéricas compostas por múltiplos de um número natural.",
               "prereqs_ilustrativos": True}},
    {"classId": "00000000-0000-0000-0000-000000000000", "quantity": 5,
     "habilidadeContext": {"habilidadeId": "EF04MA17", "unidadeTematica": {"nome": "Grandezas e medidas"},
                           "prerequisites": ["EF04MA01", "EF04MA02"], "examples": []},
     "_meta": {"ano": "quarto", "objeto_conhecimento": "Medidas de comprimento, massa, capacidade, tempo e temperatura",
               "descricao_habilidade": "Medir e estimar comprimentos (incluindo perímetros), massas e capacidades, utilizando unidades de medidas padronizadas e expressando as medidas na forma de números decimais.",
               "prereqs_ilustrativos": True}},
    {"classId": "00000000-0000-0000-0000-000000000000", "quantity": 5,
     "habilidadeContext": {"habilidadeId": "EF05MA01", "unidadeTematica": {"nome": "Números"},
                           "prerequisites": ["EF05MA02", "EF05MA03"], "examples": []}, "_meta": {"ano": "quinto",
                                                                                                 "objeto_conhecimento": "Leitura, escrita e ordenação de números naturais de até seis ordens",
                                                                                                 "descricao_habilidade": "Ler, escrever e ordenar números naturais de até a ordem das centenas de milhar, com e sem o suporte da reta numérica.",
                                                                                                 "prereqs_ilustrativos": True}},
    {"classId": "00000000-0000-0000-0000-000000000000", "quantity": 3,
     "habilidadeContext": {"habilidadeId": "EF05MA12", "unidadeTematica": {"nome": "Geometria"},
                           "prerequisites": ["EF05MA01", "EF05MA02"], "examples": []},
     "_meta": {"ano": "quinto", "objeto_conhecimento": "Plano cartesiano e deslocamento no espaço",
               "descricao_habilidade": "Associar pares ordenados de números a pontos do plano cartesiano do 1º quadrante, em situações como a localização dos vértices de um polígono.",
               "prereqs_ilustrativos": True}},
    {"classId": "00000000-0000-0000-0000-000000000000", "quantity": 5,
     "habilidadeContext": {"habilidadeId": "EF06MA14", "unidadeTematica": {"nome": "Álgebra"},
                           "prerequisites": ["EF06MA01", "EF06MA02"], "examples": []},
     "_meta": {"ano": "sexto", "objeto_conhecimento": "Propriedades da igualdade",
               "descricao_habilidade": "Reconhecer que a relação de igualdade matemática não se altera ao adicionar, subtrair, multiplicar ou dividir os seus dois membros por um mesmo número e utilizar essa noção para determinar valores desconhecidos na resolução de problemas.",
               "prereqs_ilustrativos": True}},
    {"classId": "00000000-0000-0000-0000-000000000000", "quantity": 5,
     "habilidadeContext": {"habilidadeId": "EF06MA30", "unidadeTematica": {"nome": "Probabilidade e estatística"},
                           "prerequisites": ["EF06MA01", "EF06MA02"], "examples": []}, "_meta": {"ano": "sexto",
                                                                                                 "objeto_conhecimento": "Cálculo de probabilidade como a razão entre o número de resultados favoráveis e o total de resultados possíveis em um espaço amostral equiprovável Cálculo de probabilidade por meio de muitas repetições de um experimento (frequências de ocorrências e probabilidade frequentista)",
                                                                                                 "descricao_habilidade": "Calcular a probabilidade de um evento aleatório, expressando-a por número racional (forma fracionária, decimal e percentual) e comparar esse número com a probabilidade obtida por meio de experimentos sucessivos.",
                                                                                                 "prereqs_ilustrativos": True}},
    {"classId": "00000000-0000-0000-0000-000000000000", "quantity": 5,
     "habilidadeContext": {"habilidadeId": "EF07MA01", "unidadeTematica": {"nome": "Números"},
                           "prerequisites": ["EF07MA02", "EF07MA03"], "examples": []},
     "_meta": {"ano": "setimo", "objeto_conhecimento": "Múltiplos e divisores de um número natural",
               "descricao_habilidade": "Resolver e elaborar problemas com números naturais, envolvendo as noções de divisor e de múltiplo, podendo incluir máximo divisor comum ou mínimo múltiplo comum, por meio de estratégias diversas, sem a aplicação de algoritmos.",
               "prereqs_ilustrativos": True}},
    {"classId": "00000000-0000-0000-0000-000000000000", "quantity": 3,
     "habilidadeContext": {"habilidadeId": "EF07MA19", "unidadeTematica": {"nome": "Geometria"},
                           "prerequisites": ["EF07MA01", "EF07MA02"], "examples": []}, "_meta": {"ano": "setimo",
                                                                                                 "objeto_conhecimento": "Transformações geométricas de polígonos no plano cartesiano: multiplicação das coordenadas por um número inteiro e obtenção de simétricos em relação aos eixos e à origem",
                                                                                                 "descricao_habilidade": "Realizar transformações de polígonos representados no plano cartesiano, decorrentes da multiplicação das coordenadas de seus vértices por um número inteiro.",
                                                                                                 "prereqs_ilustrativos": True}},
    {"classId": "00000000-0000-0000-0000-000000000000", "quantity": 5,
     "habilidadeContext": {"habilidadeId": "EF08MA06", "unidadeTematica": {"nome": "Álgebra"},
                           "prerequisites": ["EF08MA01", "EF08MA02"], "examples": []},
     "_meta": {"ano": "oitavo", "objeto_conhecimento": "Valor numérico de expressões algébricas",
               "descricao_habilidade": "Resolver e elaborar problemas que envolvam cálculo do valor numérico de expressões algébricas, utilizando as propriedades das operações.",
               "prereqs_ilustrativos": True}},
    {"classId": "00000000-0000-0000-0000-000000000000", "quantity": 5,
     "habilidadeContext": {"habilidadeId": "EF08MA19", "unidadeTematica": {"nome": "Grandezas e medidas"},
                           "prerequisites": ["EF08MA01", "EF08MA02"], "examples": []}, "_meta": {"ano": "oitavo",
                                                                                                 "objeto_conhecimento": "Área de figuras planas Área do círculo e comprimento de sua circunferência",
                                                                                                 "descricao_habilidade": "Resolver e elaborar problemas que envolvam medidas de área de figuras geométricas, utilizando expressões de cálculo de área (quadriláteros, triângulos e círculos), em situações como determinar medida de terrenos.",
                                                                                                 "prereqs_ilustrativos": True}},
    {"classId": "00000000-0000-0000-0000-000000000000", "quantity": 5,
     "habilidadeContext": {"habilidadeId": "EF09MA01", "unidadeTematica": {"nome": "Números"},
                           "prerequisites": ["EF09MA02", "EF09MA03"], "examples": []}, "_meta": {"ano": "nono",
                                                                                                 "objeto_conhecimento": "Necessidade dos números reais para medir qualquer segmento de reta Números irracionais: reconhecimento e localização de alguns na reta numérica",
                                                                                                 "descricao_habilidade": "Reconhecer que, uma vez fixada uma unidade de comprimento, existem segmentos de reta cujo comprimento não é expresso por número racional (como as medidas de diagonais de um polígono e alturas de um triângulo, quando se toma a medida de cada lado como unidade).",
                                                                                                 "prereqs_ilustrativos": True}},
    {"classId": "00000000-0000-0000-0000-000000000000", "quantity": 3,
     "habilidadeContext": {"habilidadeId": "EF09MA10", "unidadeTematica": {"nome": "Geometria"},
                           "prerequisites": ["EF09MA01", "EF09MA02"], "examples": []}, "_meta": {"ano": "nono",
                                                                                                 "objeto_conhecimento": "Demonstrações de relações entre os ângulos formados por retas paralelas intersectadas por uma transversal",
                                                                                                 "descricao_habilidade": "Demonstrar relações simples entre os ângulos formados por retas paralelas cortadas por uma transversal.",
                                                                                                 "prereqs_ilustrativos": True}},
    {"classId": "00000000-0000-0000-0000-000000000000", "quantity": 10,
     "habilidadeContext": {"habilidadeId": "EF09MA20", "unidadeTematica": {"nome": "Probabilidade e estatística"},
                           "prerequisites": ["EF09MA01", "EF09MA02"], "examples": []}, "_meta": {"ano": "nono",
                                                                                                 "objeto_conhecimento": "Análise de probabilidade de eventos aleatórios: eventos dependentes e independentes",
                                                                                                 "descricao_habilidade": "Reconhecer, em experimentos aleatórios, eventos independentes e dependentes e calcular a probabilidade de sua ocorrência, nos dois casos.",
                                                                                                 "prereqs_ilustrativos": True}}]
    x = random.randint(0,14)
    return x
